In [1]:
import open3d as o3d
import numpy as np
import PIL.Image
import wget

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [58]:
pcd = o3d.io.read_point_cloud("./dataset/heart.pcd")
print(pcd)

PointCloud with 151408 points.


In [59]:
pcd = o3d.io.read_point_cloud("./dataset/heart.xyz", format='xyz')
print(pcd)

PointCloud with 126866 points.


In [60]:
mesh = o3d.io.read_triangle_mesh("./dataset/heart.ply")

In [61]:
print(pcd)

PointCloud with 126866 points.


In [62]:
pcd = mesh.sample_points_uniformly(number_of_points=500)

In [63]:
print(np.asarray(pcd.points))

[[ 20.01316167 -28.65980402  -3.81129506]
 [ 20.54212153 -27.88828152  -2.29410453]
 [  5.84757258 -27.10962507  -3.58764915]
 ...
 [  6.17132016  28.2061092   -8.70640765]
 [  1.447408    28.72727687  -9.98498636]
 [  1.21934912  28.9016489   -6.28888384]]


In [64]:
o3d.visualization.draw_geometries([pcd])

In [65]:
# Voxel downsampling

In [66]:
print("Downsample the point cloud with a voxel of 0.05")
downpcd = pcd.voxel_down_sample(voxel_size=0.05)

Downsample the point cloud with a voxel of 0.05


In [67]:
print(downpcd)
print(np.asarray(downpcd.points))

PointCloud with 500 points.
[[  1.21934912  28.9016489   -6.28888384]
 [  6.17132016  28.2061092   -8.70640765]
 [ -7.50683293  28.1433714   -6.9686807 ]
 ...
 [ -1.15633885 -25.74256954  -5.09336868]
 [ 20.81606663 -19.36621891  -0.24309243]
 [ 19.39706664 -25.36742932  -7.43571719]]


In [68]:
o3d.visualization.draw_geometries([downpcd],width=1920, height=1080, left=50, top=50)

In [69]:
aabb = pcd.get_axis_aligned_bounding_box()
aabb.color = (1, 0, 0)
obb = pcd.get_oriented_bounding_box()
obb.color = (0, 1, 0)

In [70]:
o3d.visualization.draw_geometries([downpcd, aabb, obb])

In [71]:
path = "./dataset/heart.ply"
mesh = o3d.io.read_triangle_mesh(path)
mesh.compute_vertex_normals()

TriangleMesh with 103346 points and 203176 triangles.

In [72]:
mesh.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh])

In [73]:
color = mesh.compute_vertex_normals()

In [74]:
print("Painting")

#paint_uniform_color paints all the points to a uniform color. The color is in RGB space, [0, 1] range.
color.paint_uniform_color([0.6, 0.4, 0.4])
o3d.visualization.draw_geometries([color], width=1920, height=1080, left=50, top=50)

Painting
